### PR TITLE
Created workflow to build and test application

### LINKED ISSUE #10: SUGGESTION: Add a GitHub Workflow to run Unit Tests on every commit
We can create a Workflow action file which runs our usual `npm run test` upon every commit to the `main` branch.
Could also run those checks for Pull Requests.

### PR DESCRIPTION
**Pull request by adityaraute**
Fixes #10 

I have added a GitHub workflow to the fork.
The main aim of this is to ensure all pushes and PRs successfully pass the unit tests defined.

### CODE REVIEW

**Review by bob-fornal — APPROVED** [review]

**Review by bob-fornal — COMMENTED** [review]
Add the name to the job build

**Comment by adityaraute** [comment]
Do you prefer the merge commit messages to be like this one?
I personally prefer a Squash and Merge, with the purpose of the changes as the message.

**Comment by bob-fornal** [comment]
I actually prefer the PR Template to describe the work done. I've added a new PR, cleaned up the YML script a but, and changed the branch protection rules for MAIN. I won't know if the rules are exactly right until we try merging again, but they will be MORE restrictive rather than less.

**Comment by adityaraute** [comment]
Makes sense. Thanks!

**Pull request merged**
